<?php

namespace Proxies\__CG__\CEG\ArticleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \CEG\ArticleBundle\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclTitle', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclContent', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclDate', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclLike', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'images', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'files');
        }

        return array('__isInitialized__', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclTitle', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclContent', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclDate', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'artclLike', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'images', '' . "\0" . 'CEG\\ArticleBundle\\Entity\\Article' . "\0" . 'files');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtclTitle($artclTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtclTitle', array($artclTitle));

        return parent::setArtclTitle($artclTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtclTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtclTitle', array());

        return parent::getArtclTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtclContent($artclContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtclContent', array($artclContent));

        return parent::setArtclContent($artclContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtclContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtclContent', array());

        return parent::getArtclContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtclDate($artclDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtclDate', array($artclDate));

        return parent::setArtclDate($artclDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtclDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtclDate', array());

        return parent::getArtclDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtclLike($artclLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtclLike', array($artclLike));

        return parent::setArtclLike($artclLike);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtclLike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtclLike', array());

        return parent::getArtclLike();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\CEG\ArticleBundle\Entity\Image $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($images));

        return parent::addImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\CEG\ArticleBundle\Entity\Image $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($images));

        return parent::removeImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

}
